import "dotenv/config";
import { randomUUID } from "crypto";
import express, { type Request, type Response } from "express";
import rateLimit from "express-rate-limit";
import helmet from "helmet";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";

import { validateEnv, config } from "./config.js";
import { tokenContext } from "./context.js";
import { registerTimesheetTools } from "./tools/timesheets.js";
import { registerCapacityPlannerTools } from "./tools/capacity-planner.js";

// ─── Startup ──────────────────────────────────────────────────────────────────

validateEnv();

// ─── Security constants ───────────────────────────────────────────────────────

// [SEC-1] Ephemeral proxy secret returned to mcp-remote during /oauth/register.
// mcp-remote will include it in token requests, but our proxy ignores it and
// uses the real TEMPO_CLIENT_SECRET from config instead.
// This prevents the real secret from ever being exposed over the network.
const PROXY_CLIENT_SECRET = randomUUID();

// [SEC-2] Detect production (HTTPS) to set the Secure cookie flag.
const IS_HTTPS = config.server.publicUrl.startsWith("https://");

// [SEC-3] Maximum concurrent MCP sessions (DoS protection).
const MAX_SESSIONS = 200;

// [SEC-6] Maximum length of OAuth state parameter stored in cookie.
// HTTP cookies are limited to ~4096 bytes; a very long state would break the flow.
const MAX_STATE_LENGTH = 512;

// [SEC-M3] Maximum idle lifetime for an MCP session before it is force-purged.
// Prevents stale sessions (from crashed clients) from permanently exhausting MAX_SESSIONS.
// Configurable via SESSION_TTL_MS env var (milliseconds) — default 24 hours.
// Railway restarts containers and kills idle SSE streams; a longer TTL reduces forced re-auths.
const SESSION_TTL_MS =
  parseInt(process.env["SESSION_TTL_MS"] ?? "", 10) || 24 * 60 * 60 * 1000;

// ─── MCP server factory ───────────────────────────────────────────────────────
// One McpServer instance per StreamableHTTP session — required by the SDK.

function createMcpServer(): McpServer {
  const server = new McpServer({ name: "tempo-mcp", version: "1.0.0" });
  registerTimesheetTools(server);
  registerCapacityPlannerTools(server);
  return server;
}

// ─── Session tracking ─────────────────────────────────────────────────────────
// Each MCP session gets a unique ID generated by StreamableHTTPServerTransport.
// All requests for a session carry the Mcp-Session-Id header; we look up the
// matching transport and re-inject the Tempo Bearer token via AsyncLocalStorage.

const transports = new Map<string, StreamableHTTPServerTransport>();
const sessionTokens = new Map<string, string>();
// [SEC-M3] Track last activity time per session for TTL eviction.
const sessionLastActive = new Map<string, number>();

// ─── OAuth cookie helpers ─────────────────────────────────────────────────────
// Tempo does not relay the OAuth `state` parameter in its callback, so we
// cannot encode session data there. Instead we use a short-lived HttpOnly
// cookie set in /oauth/authorize and read in /oauth/callback.
// Each user's browser carries its own cookie → concurrent users are isolated.

interface OAuthSession {
  state: string;       // original mcp-remote state (needed for PKCE verification)
  redirectUri: string; // mcp-remote's local callback URL
}

function readOAuthSessionCookie(req: Request): OAuthSession | null {
  const raw = req.headers.cookie
    ?.split(";")
    .map((c) => c.trim())
    .find((c) => c.startsWith("oauth_session="))
    ?.slice("oauth_session=".length);

  if (!raw) return null;
  try {
    const parsed = JSON.parse(decodeURIComponent(raw)) as unknown;
    // [SEC-M2] Runtime type validation — the cast alone provides no safety at runtime.
    if (
      typeof parsed !== "object" ||
      parsed === null ||
      typeof (parsed as Record<string, unknown>)["state"] !== "string" ||
      typeof (parsed as Record<string, unknown>)["redirectUri"] !== "string"
    ) {
      return null;
    }
    return parsed as OAuthSession;
  } catch {
    return null;
  }
}

// [SEC-4] Validate that the OAuth callback redirect URI targets localhost only.
// mcp-remote always uses http://localhost:<port> or http://127.0.0.1:<port>.
// Rejecting any other host prevents open-redirect / auth-code interception attacks.
function isLocalhostUri(uri: string): boolean {
  try {
    const { hostname, protocol } = new URL(uri);
    return (
      protocol === "http:" &&
      (hostname === "localhost" || hostname === "127.0.0.1")
    );
  } catch {
    return false;
  }
}

// Cookie flags — add Secure in production (HTTPS) to prevent transmission over HTTP.
function oauthCookieFlags(maxAge: number): string {
  const base = `HttpOnly; SameSite=Lax; Max-Age=${maxAge}; Path=/`;
  return IS_HTTPS ? `${base}; Secure` : base;
}

// ─── Rate limiters ────────────────────────────────────────────────────────────
// [SEC-5] Protect OAuth endpoints from flooding / Tempo API abuse.

const oauthLimiter = rateLimit({
  windowMs: 60 * 1000,  // 1-minute window
  max: 30,              // max 30 requests per IP per minute
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Too many requests — please try again in a minute." },
});

const mcpLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 120,             // max 120 MCP requests per IP per minute
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Too many requests — please try again in a minute." },
});

// ─── Express app ──────────────────────────────────────────────────────────────
// No cors() — mcp-remote is a Node.js process, not a browser, so CORS headers
// serve no legitimate purpose and only widen the attack surface.

const app = express();

// [SEC-A] Trust the first reverse proxy so express-rate-limit reads
// X-Forwarded-For instead of the proxy's own IP. Without this, all users
// behind nginx share a single rate-limit bucket.
app.set("trust proxy", 1);

// [SEC-B] Security headers (X-Content-Type-Options, X-Frame-Options,
// Referrer-Policy, etc.) for the browser-facing OAuth pages.
app.use(helmet());

app.use(express.json({ limit: "64kb" }));
app.use(express.urlencoded({ extended: false, limit: "16kb" })); // [SEC-L2] false = flat key-value only (no nested qs objects)

// ─── Health ───────────────────────────────────────────────────────────────────

app.get("/health", (_req: Request, res: Response): void => {
  res.json({ status: "ok", service: "tempo-mcp" }); // [SEC-I2] transport type omitted — unnecessary info disclosure
});

// ─── OAuth 2.0 Discovery (RFC 8414) ──────────────────────────────────────────
// mcp-remote fetches this to discover authorization and token endpoints.

app.get("/.well-known/oauth-authorization-server", (_req: Request, res: Response): void => {
  const base = config.server.publicUrl;
  res.json({
    issuer: "https://api.tempo.io",
    authorization_endpoint: `${base}/oauth/authorize`,
    token_endpoint: `${base}/oauth/token`,
    registration_endpoint: `${base}/oauth/register`,
    response_types_supported: ["code"],
    grant_types_supported: ["authorization_code", "refresh_token"],
    code_challenge_methods_supported: ["S256"],
  });
});

// ─── OAuth Dynamic Client Registration (RFC 7591) ────────────────────────────
// mcp-remote calls this before OAuth to register itself as a client.
// [SEC-1] We return our client_id but an ephemeral proxy secret — never the
// real TEMPO_CLIENT_SECRET. mcp-remote will send PROXY_CLIENT_SECRET in token
// requests; our /oauth/token handler ignores it and uses the real secret from config.

app.post("/oauth/register", oauthLimiter, (req: Request, res: Response): void => {
  const body = req.body as {
    redirect_uris?: string[];
    client_name?: string;
    grant_types?: string[];
    response_types?: string[];
    token_endpoint_auth_method?: string;
  };

  res.status(201).json({
    client_id: config.tempo.clientId,
    client_secret: PROXY_CLIENT_SECRET,          // ✅ ephemeral — not the real secret
    client_id_issued_at: Math.floor(Date.now() / 1000),
    client_secret_expires_at: 0,
    redirect_uris: body.redirect_uris ?? [],
    client_name: body.client_name ?? "mcp-remote",
    grant_types: body.grant_types ?? ["authorization_code", "refresh_token"],
    response_types: body.response_types ?? ["code"],
    token_endpoint_auth_method: body.token_endpoint_auth_method ?? "client_secret_post",
  });
});

// ─── OAuth Authorize redirect ─────────────────────────────────────────────────
// mcp-remote sends users here. We forward to Tempo's authorize URL, injecting
// our client_id and jira_url. The original state + redirect_uri are saved in
// a short-lived HttpOnly cookie so /oauth/callback can relay them back.

app.get("/oauth/authorize", oauthLimiter, (req: Request, res: Response): void => {
  const state = (req.query["state"] as string | undefined) ?? "";
  const originalRedirectUri = req.query["redirect_uri"] as string | undefined;
  const responseType = (req.query["response_type"] as string | undefined) ?? "code";
  const codeChallenge = req.query["code_challenge"] as string | undefined;
  const codeChallengeMethod = req.query["code_challenge_method"] as string | undefined;

  // [SEC-6] Reject oversized state values before storing them in the cookie.
  if (state.length > MAX_STATE_LENGTH) {
    res.status(400).json({ error: "state parameter too long" });
    return;
  }

  // [SEC-L4] Require redirect_uri — failing early avoids bouncing the user to Tempo
  // only to error out at /oauth/callback with a missing cookie.
  if (!originalRedirectUri) {
    res.status(400).json({ error: "redirect_uri is required" });
    return;
  }

  // [SEC-4] Reject non-localhost redirect URIs at the source.
  if (!isLocalhostUri(originalRedirectUri)) {
    res.status(400).json({ error: "redirect_uri must target localhost" });
    return;
  }

  // [SEC-M5] Whitelist response_type — only Authorization Code flow is supported.
  if (responseType !== "code") {
    res.status(400).json({ error: "unsupported_response_type" });
    return;
  }

  // [SEC-M5] Whitelist code_challenge_method — only S256 is supported (per discovery endpoint).
  if (codeChallengeMethod !== undefined && codeChallengeMethod !== "S256") {
    res.status(400).json({ error: "unsupported_code_challenge_method" });
    return;
  }

  const session: OAuthSession = { state, redirectUri: originalRedirectUri };
  res.setHeader(
    "Set-Cookie",
    `oauth_session=${encodeURIComponent(JSON.stringify(session))}; ${oauthCookieFlags(600)}`
  );

  const params = new URLSearchParams({
    client_id: config.tempo.clientId,
    jira_url: config.jiraUrl,
    redirect_uri: config.oauth.redirectUri,
    state,
    response_type: responseType,
  });

  if (codeChallenge) params.set("code_challenge", codeChallenge);
  if (codeChallengeMethod) params.set("code_challenge_method", codeChallengeMethod);

  res.redirect(`${config.tempo.authorizeUrl}?${params.toString()}`);
});

// ─── OAuth Callback relay ─────────────────────────────────────────────────────
// Tempo redirects here after the user authorises. We read the cookie set in
// /oauth/authorize and relay the code + original state back to mcp-remote.

app.get("/oauth/callback", oauthLimiter, (req: Request, res: Response): void => {
  const code = req.query["code"] as string | undefined;
  const error = req.query["error"] as string | undefined;

  const session = readOAuthSessionCookie(req);
  if (!session) {
    res.status(400).send(
      "OAuth session cookie missing. Please restart the connection from Claude Desktop."
    );
    return;
  }

  // [SEC-4] Double-check the stored URI before redirecting — defence in depth.
  if (!isLocalhostUri(session.redirectUri)) {
    res.setHeader("Set-Cookie", `oauth_session=; ${oauthCookieFlags(0)}`);
    res.status(400).send("Invalid OAuth session — redirect URI rejected.");
    return;
  }

  // Clear the cookie immediately — it is single-use.
  res.setHeader("Set-Cookie", `oauth_session=; ${oauthCookieFlags(0)}`);

  const relay = new URLSearchParams();
  if (code) relay.set("code", code);
  relay.set("state", session.state);
  if (error) relay.set("error", error);

  console.error(`[oauth/callback] Relaying to: ${session.redirectUri}`);
  res.redirect(`${session.redirectUri}?${relay.toString()}`);
});

// ─── OAuth Token Proxy ────────────────────────────────────────────────────────
// mcp-remote calls this to exchange an authorization code or refresh token.
// We inject our real client credentials and proxy the request to Tempo.
// Whatever client_secret mcp-remote sends is deliberately ignored.

app.post("/oauth/token", oauthLimiter, async (req: Request, res: Response): Promise<void> => {
  type TokenBody = {
    grant_type?: string;
    code?: string;
    redirect_uri?: string;
    refresh_token?: string;
    code_verifier?: string;
  };

  const { grant_type, code, refresh_token, code_verifier } = req.body as TokenBody;

  if (!grant_type) {
    res.status(400).json({ error: "missing grant_type" });
    return;
  }

  // [SEC-M1] Whitelist allowed grant types — reject anything unexpected.
  const ALLOWED_GRANT_TYPES = ["authorization_code", "refresh_token"];
  if (!ALLOWED_GRANT_TYPES.includes(grant_type)) {
    res.status(400).json({ error: "unsupported_grant_type" });
    return;
  }

  const body = new URLSearchParams({ grant_type });
  body.set("client_id", config.tempo.clientId);
  body.set("client_secret", config.tempo.clientSecret); // real secret — never sent to clients
  body.set("redirect_uri", config.oauth.redirectUri);   // must match Tempo's registered URI exactly
  if (code) body.set("code", code);
  if (refresh_token) body.set("refresh_token", refresh_token);
  if (code_verifier) body.set("code_verifier", code_verifier); // PKCE

  // [SEC-M6] Abort the token exchange if Tempo doesn't respond within 10 seconds.
  // Interactive OAuth flow — shorter timeout than the API (30s) is appropriate.
  const tokenController = new AbortController();
  const tokenTimeoutId = setTimeout(() => tokenController.abort(), 10_000);

  try {
    const upstream = await fetch(config.tempo.tokenUrl, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: body.toString(),
      signal: tokenController.signal,
    });

    const data: unknown = await upstream.json();
    if (!upstream.ok) {
      console.error(`[oauth/token] Tempo error ${upstream.status}:`, JSON.stringify(data));
    }
    res.status(upstream.status).json(data);
  } catch (err) {
    if (err instanceof Error && err.name === "AbortError") {
      console.error("[oauth/token] Token exchange timed out");
      res.status(504).json({ error: "upstream_timeout" });
      return;
    }
    console.error("[oauth/token] Proxy error:", err);
    // [SEC] Do not expose internal error details (host, stack trace) to the client.
    res.status(502).json({ error: "upstream_error" });
  } finally {
    clearTimeout(tokenTimeoutId);
  }
});

// ─── MCP endpoint (StreamableHTTP) ───────────────────────────────────────────
// Single endpoint handling POST (init + messages), GET (event stream),
// and DELETE (session termination) as per the MCP StreamableHTTP spec.
// The Tempo access token is read from Authorization: Bearer on the first POST
// and stored per-session; all subsequent requests re-inject it via AsyncLocalStorage.

app.all("/mcp", mcpLimiter, async (req: Request, res: Response): Promise<void> => {
  const sessionId = req.headers["mcp-session-id"] as string | undefined;

  // ── Route to existing session ──────────────────────────────────────────────
  if (sessionId) {
    const transport = transports.get(sessionId);
    const token = sessionTokens.get(sessionId);
    if (!transport || !token) {
      res.status(404).json({ error: "Session not found" }); // [SEC] don't echo sessionId
      return;
    }
    sessionLastActive.set(sessionId, Date.now()); // [SEC-M3] refresh activity timestamp

    // [KEEP-ALIVE] For SSE streams (GET), emit an SSE comment every 25 seconds.
    // Railway's reverse proxy closes idle long-lived HTTP connections after ~30s.
    // A keep-alive comment keeps the TCP connection alive without affecting the
    // MCP protocol (SSE comments starting with ":" are ignored by clients).
    let heartbeatInterval: NodeJS.Timeout | undefined;
    if (req.method === "GET") {
      heartbeatInterval = setInterval(() => {
        if (!res.writableEnded && res.headersSent) {
          res.write(": keep-alive\n\n");
        }
      }, 25_000);
    }

    // [SEC-M7] Express 4 doesn't catch async errors — an unhandled rejection crashes Node.js 18.
    try {
      await tokenContext.run(token, () => transport.handleRequest(req, res, req.body));
    } catch (err) {
      console.error("[mcp] Transport error on existing session:", err);
      if (!res.headersSent) res.status(500).json({ error: "internal_error" });
    } finally {
      if (heartbeatInterval) clearInterval(heartbeatInterval);
    }
    return;
  }

  // ── New session — only POST is valid for initialisation ────────────────────
  if (req.method !== "POST") {
    res.status(400).json({ error: "New sessions must be initialised with POST" });
    return;
  }

  // [SEC-3] Refuse new connections when the session ceiling is reached.
  if (transports.size >= MAX_SESSIONS) {
    res.status(503).json({ error: "Server at maximum session capacity. Try again later." });
    return;
  }

  const authHeader = (req.headers["authorization"] as string | undefined) ?? "";
  const token = authHeader.replace(/^Bearer\s+/i, "").trim();
  if (!token) {
    res.status(401).json({ error: "Missing Authorization: Bearer <tempo_token>" });
    return;
  }

  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: () => randomUUID(),
    onsessioninitialized: (newSessionId) => {
      transports.set(newSessionId, transport);
      sessionTokens.set(newSessionId, token);
      sessionLastActive.set(newSessionId, Date.now()); // [SEC-M3]
      console.error(`[mcp] New session: ${newSessionId} (active: ${transports.size})`);
    },
  });

  transport.onclose = (): void => {
    const sid = transport.sessionId;
    if (sid) {
      transports.delete(sid);
      sessionTokens.delete(sid);
      sessionLastActive.delete(sid); // [SEC-M3]
      console.error(`[mcp] Session closed: ${sid}`);
    }
  };

  // [SEC-M7/L8] Express 4 doesn't catch async errors — an unhandled rejection crashes Node.js 18.
  // server.connect() is included here because it can also throw (e.g. SDK initialisation failure).
  try {
    const server = createMcpServer();
    await server.connect(transport);
    await tokenContext.run(token, () => transport.handleRequest(req, res, req.body));
  } catch (err) {
    console.error("[mcp] Transport error on new session:", err);
    if (!res.headersSent) res.status(500).json({ error: "internal_error" });
  }
});

// ─── Start ────────────────────────────────────────────────────────────────────

// [SEC-M3] Periodic cleanup of sessions that exceeded SESSION_TTL_MS without activity.
// Runs every 30 minutes — handles crashed clients that never fire transport.onclose.
setInterval(() => {
  const now = Date.now();
  for (const [sid, lastActive] of sessionLastActive) {
    if (now - lastActive > SESSION_TTL_MS) {
      transports.delete(sid);
      sessionTokens.delete(sid);
      sessionLastActive.delete(sid);
      console.error(`[mcp] Session evicted (TTL exceeded): ${sid}`);
    }
  }
}, 30 * 60 * 1000).unref(); // .unref() so the interval doesn't keep the process alive on shutdown

const { port } = config.server;
app.listen(port, () => {
  console.error(`[tempo-mcp] Listening on port ${port}`);
  console.error(`[tempo-mcp] MCP endpoint   : ${config.server.publicUrl}/mcp`);
  console.error(`[tempo-mcp] OAuth discovery: ${config.server.publicUrl}/.well-known/oauth-authorization-server`);
  console.error(`[tempo-mcp] Health         : ${config.server.publicUrl}/health`);
  console.error(`[tempo-mcp] HTTPS mode     : ${IS_HTTPS}`);
});
